In [17]:
import pandas as pd
df=pd.read_csv("raw_data.csv")
df.isnull()
df.isnull().sum()
df.dropna()  #drop raw
df.dropna(axis=1) #col raw
df.fillna(0)

age_mean=df["age"].mean()
cleaned_data=df.copy()
age_mean=cleaned_data["age"].mean()
cleaned_data["age"]=cleaned_data["age"].fillna(age_mean)
cleaned_data
df.ffill()
df.bfill()

    id          name   age country   gender
0    1      John Doe  29.0     USA     Male
1    1      John Doe  29.0     USA     Male
2    2    Jane Smith  34.0  Canada   Female
3    3          Alex  34.0     USA  Unknown
4    4  Maria Garcia  34.0   Spain   Female
5    5        Li Wei  27.0   China     Male
6    6    Ahmed Khan  45.0   India   Female
7    7    Ahmed Khan  38.0     USA     Male
8    8    Rachel Lee  29.0     USA   Female
9    9   Carlos Ruiz  31.0  Mexico      NaN
10  10   Emily Davis  31.0     USA      NaN

In [15]:
df

    id          name   age country   gender
0    1      John Doe  29.0     USA     Male
1    1      John Doe  29.0     USA     Male
2    2    Jane Smith   NaN  Canada   Female
3    3          Alex   NaN     USA  Unknown
4    4  Maria Garcia  34.0   Spain   Female
5    5        Li Wei  27.0   China     Male
6    6           NaN  45.0   India   Female
7    7    Ahmed Khan  38.0     NaN     Male
8    8    Rachel Lee  29.0     USA   Female
9    9   Carlos Ruiz   NaN  Mexico      NaN
10  10   Emily Davis  31.0     USA      NaN