In [19]:
import pandas as pd
# Transforming Data
  #• Applying Functions
df=pd.read_csv("raw_data_with_more_columns.csv")
df1=df.copy()
df1['Age_plus_10']=df1['age'].apply(lambda x : x+10)
#→ mapping mein na milne wali values → NaN
df1['country'] = df1['country'].map({'USA': 'america','India': 'bharat'}) 
# .assign() DataFrame mein naya column add karne ke liye use hota hai.
df1.assign(new_income=df["age"]*1.1)
df['country']=df['country'].replace({'India':'IN','USA':'US'})
df

,id,name,age,country,gender,income,occupation,experience_years
0,1,John Doe,29.0,US,Male,55000,Developer,3
1,1,John Doe,29.0,US,Male,55000,Developer,3
2,2,Jane Smith,NaN,Canada,Female,62000,Teacher,5
3,3,Alex,NaN,US,Unknown,48000,Designer,2
4,4,Maria Garcia,34.0,Spain,Female,72000,Engineer,7
5,5,Li Wei,27.0,China,Male,68000,Manager,6
6,6,NaN,45.0,IN,Female,85000,Doctor,12
7,7,Ahmed Khan,38.0,NaN,Male,59000,Analyst,4
8,8,Rachel Lee,29.0,US,Female,64000,Consultant,5
9,9,Carlos Ruiz,NaN,Mexico,NaN,75000,Manager,8
10,10,Emily Davis,31.0,US,NaN,71000,Engineer,6

In [4]:
df

,id,name,age,country,gender,income,occupation,experience_years
0,1,John Doe,29.0,USA,Male,55000,Developer,3
1,1,John Doe,29.0,USA,Male,55000,Developer,3
2,2,Jane Smith,NaN,Canada,Female,62000,Teacher,5
3,3,Alex,NaN,USA,Unknown,48000,Designer,2
4,4,Maria Garcia,34.0,Spain,Female,72000,Engineer,7
5,5,Li Wei,27.0,China,Male,68000,Manager,6
6,6,NaN,45.0,India,Female,85000,Doctor,12
7,7,Ahmed Khan,38.0,NaN,Male,59000,Analyst,4
8,8,Rachel Lee,29.0,USA,Female,64000,Consultant,5
9,9,Carlos Ruiz,NaN,Mexico,NaN,75000,Manager,8
10,10,Emily Davis,31.0,USA,NaN,71000,Engineer,6