In [ ]:
import pandas as pd
df=pd.read_csv("raw_data_with_more_columns.csv")
df_renamed=df.rename(columns={"name":"full name"})

df_recorded=df_renamed[["country", "age", "income", "occupation"]]
df_recorded

df_filtered=df_renamed[df_renamed["age"]>20]
df_filtered
df_reset=df_filtered.reset_index(drop=True)
df_reset

,id,full name,age,country,gender,income,occupation,experience_years
0,1,John Doe,29.0,USA,Male,55000,Developer,3
1,1,John Doe,29.0,USA,Male,55000,Developer,3
2,4,Maria Garcia,34.0,Spain,Female,72000,Engineer,7
3,5,Li Wei,27.0,China,Male,68000,Manager,6
4,6,NaN,45.0,India,Female,85000,Doctor,12
5,7,Ahmed Khan,38.0,NaN,Male,59000,Analyst,4
6,8,Rachel Lee,29.0,USA,Female,64000,Consultant,5
7,10,Emily Davis,31.0,USA,NaN,71000,Engineer,6

In [ ]:
# 2.Sorting / Ranking
# Sorting - values & index 
df2=df.copy()
df2.sort_values("income")
df2.sort_values("income",ascending=False)
df2.sort_values(["age","income"])


sorted_df2=df2.sort_values(["age","income"])
sorted_df2.sort_index()

# Ranking 
df2["Ranking"]=df2["income"].rank(ascending=False,method="dense")
df2["Ranking"]=df2["income"].rank(ascending=False,method="min")
df2["Ranking"]=df2["income"].rank(ascending=False,method="max")
df2

,id,name,age,country,gender,income,occupation,experience_years,Ranking
0,1,John Doe,29.0,USA,Male,55000,Developer,3,9.0
1,1,John Doe,29.0,USA,Male,55000,Developer,3,9.0
2,2,Jane Smith,NaN,Canada,Female,62000,Teacher,5,7.0
3,3,Alex,NaN,USA,Unknown,48000,Designer,2,10.0
4,4,Maria Garcia,34.0,Spain,Female,72000,Engineer,7,3.0
5,5,Li Wei,27.0,China,Male,68000,Manager,6,5.0
6,6,NaN,45.0,India,Female,85000,Doctor,12,1.0
7,7,Ahmed Khan,38.0,NaN,Male,59000,Analyst,4,8.0
8,8,Rachel Lee,29.0,USA,Female,64000,Consultant,5,6.0
9,9,Carlos Ruiz,NaN,Mexico,NaN,75000,Manager,8,2.0
10,10,Emily Davis,31.0,USA,NaN,71000,Engineer,6,4.0